### ISSUE TITLE
nearby venues 

### ISSUE THREAD

**Issue by SebasFC** [jmlich/foursail#1]
Hi, I was eager to use the app, but after activating GPS the App does not locate me. Is there anything else I need to do?

**Comment by jmlich** [comment]
The app takes position from QtPositioning module. Check if positioning works in other apps (e.g. Jolla Maps). Getting first fix may take up to 45 minutes If you did'nt agreed with Jolla Maps conditions and/or you are not connected to the internet.

**Comment by SebasFC** [comment]
Solved. But I have a new interesting foursquare question.
