### ISSUE TITLE
Specials

### ISSUE THREAD

**Issue by SebasFC** [jmlich/foursail#2]
Just found someone on Twitter from foursquareAPI saying it should be easy to add the possibility of enjoying discounts and offers from Stores through Foursail if you add them 
(API Endpoint specials)

That was one of the main reasons to have foursquare. check in and get %off or a free drink for sharing you've been somewhere.

**Comment by jmlich** [comment]
As far as I remember, specials are already implemented. In the list of nearby venues should be some symbol (star?) when special available. You should see description of special after checkin at the venue.

**Comment by SebasFC** [comment]
OH thank you. I am probably looking for specials in a place with no special.

**Comment by jmlich** [comment]
I think, there could be some improvements in listing of specials. Feel free to send an patch. Personally, I don't use that feature much.
