### ISSUE TITLE
Points - gamification - competition

### ISSUE THREAD

**Issue by SebasFC** [jmlich/foursail#3]
I can see the points earned after I check-in, but another cool thing of foursquare was the (un)healthy competitions with your friends to see who discovered the most new places.
A weekly scoreboard where you can see your current weekly points compared to your friends.

**Comment by jmlich** [comment]
The scoreboard is not available in API anymore.

See https://developer.foursquare.com/docs/users/leaderboard

**Comment by SebasFC** [comment]
I am learning. But... couldn't it be on the Swarm part of 4sq?

**Comment by jmlich** [comment]
Then feel free to reopen this issue and send URL of related API endpoint.
